[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Specify the Solidity compiler version
[profile.default.compiler]
version = "0.8.18"

# Specify the EVM version
[profile.default.evm]
version = "shanghai"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
